/// Flutter icons MyCustomIcons1
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons1
///      fonts:
///       - asset: fonts/MyCustomIcons1.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class MyCustomIcons1 {
  MyCustomIcons1._();

  static const _kFontFam = 'MyCustomIcons1';
  static const _kFontPkg = null;

  static const IconData wallet = const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop = const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = const IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money2 = const IconData(0xf0d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticket = const IconData(0xf145, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = const IconData(0xf309, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_circled = const IconData(0xf30a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = const IconData(0xf30c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_circled = const IconData(0xf30d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
